### ISSUE TITLE
Rename Exported Types 

### ISSUE THREAD

**Issue by dominicboston-kaluza** [kenneth-gray/data-mocks-server#61]
Work in progress issue - Suggestion for renaming types to make them more useful for external UI developers.

**Existing exports that are fine**
```
Options
Mock 
GraphQlMock
HttpMock
```

**Rename** 
`Scenario` --> `ScenarioMocks` 

**Add**
```
Scenario = {
        id:string;
        label: string;
        isChecked: boolean;
    }
```
```
ScenarioMock = {
        id:string;
        label: string;
        selected: boolean;
    }
```
```
ScenarioGroup = {
    id:string;
    label: string;
    noneChecked: boolean  //Not sure this is needed, easy enough to check in a util and could get out of date if developer is poor.
    scenarios: Scenario[]
}
```
```
ScenarioMockGroup =  {
    id:string;
    label: string;
    scenarios: ScenarioMock[];
};
```

`ScenarioResponse` --> What the `/scenario` endpoint returns`

```
ScenarioResponse = { 
        groups: ScenarioGroup[]
        other: Scenario[]
}
```

**Naming convention**

Use the word `Mock` in types when referring to a mock type such as `ScenarioMockGroup` and omit `Mock` when referring to the UI type such as `ScenarioGroup`

Export the singular instead of the multiple. This allows dev's to write `Group[]` if they need the multiple. But they can also access the singular without doing `type Group = [Groups]`. The singular is very useful in components that only handle a single group

**Comment by kenneth-gray** [comment]
https://github.com/kenneth-gray/scenario-mock-server now exists - check out the exported types and let me know if I've missed something important. Note that the "group" concept does not exist...yet. If there's a good case for it I'd happily entertain putting it back.
