### ISSUE TITLE
graph-ql.ts and http.ts typescript errors

### ISSUE THREAD

**Issue by dominicboston-kaluza** [kenneth-gray/data-mocks-server#62]
Raising this issue as I'm really unsure on how to fix this. Just cloned master and ran `yarn` then `yarn example` but cannot run due to errors. 

![image](https://user-images.githubusercontent.com/97444214/182602513-63256d4b-6ad7-4580-bcf2-02447d264612.png)

![image](https://user-images.githubusercontent.com/97444214/182602604-5518299c-b188-4d55-997b-aa40a13a5712.png)

**Comment by kenneth-gray** [comment]
Cheers for this - this repo uses `npm` instead of `yarn` (see the lock file), so that'll be why!

**Comment by dominicboston-kaluza** [comment]
Oops! My bad.
